server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
#defining the configuration path of github
  cloud:
    config:
      server:
        git:
          uri: https://github.com/realarnab/microservices-config-server
          clone-on-start: true